# Generated by Django 2.0.7 on 2018-07-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dish_type', models.CharField(choices=[('SOUP', 'Soup'), ('GARNISH', 'Garnish'), ('MAIN', 'Meat'), ('MAIN', 'Main'), ('SALAD', 'Salad')], max_length=7)),
                ('difficulty', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('priority', models.IntegerField(default=50)),
                ('last_used_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='season',
            field=models.ManyToManyField(to='dishes.Season'),
        ),
    ]
