# Generated by Django 2.0.7 on 2018-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='season',
            field=models.IntegerField(choices=[(0, 'Any'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')], default=0),
        ),
    ]
