# Generated by Django 2.0.7 on 2018-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_diet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='raw',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
